import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export interface Complaint {
  id: string;
  user_id: string;
  reference_id: string;
  title: string;
  description: string;
  category: string;
  priority: "low" | "medium" | "high";
  status: "new" | "in_review" | "in_progress" | "resolved" | "closed";
  anonymous: boolean;
  attachment_urls?: string[];
  created_at: string;
  updated_at: string;
}

export interface ComplaintComment {
  id: string;
  complaint_id: string;
  user_id: string;
  comment: string;
  is_admin: boolean;
  created_at: string;
  profiles?: {
    name: string;
  };
}

export interface CallRequest {
  id: string;
  complaint_id: string;
  user_id: string;
  status: "pending" | "scheduled" | "completed" | "cancelled";
  preferred_time: string | null;
  notes: string | null;
  admin_notes: string | null;
  scheduled_time: string | null;
  created_at: string;
  updated_at: string;
}

export const useComplaints = () => {
  return useQuery({
    queryKey: ["complaints"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("complaints")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data as Complaint[];
    },
  });
};

export const useComplaint = (id: string) => {
  return useQuery({
    queryKey: ["complaint", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("complaints")
        .select("*")
        .eq("id", id)
        .single();

      if (error) throw error;
      return data as Complaint;
    },
    enabled: !!id,
  });
};

export const useComplaintComments = (complaintId: string) => {
  return useQuery({
    queryKey: ["complaint-comments", complaintId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("complaint_comments")
        .select("*")
        .eq("complaint_id", complaintId)
        .order("created_at", { ascending: true });

      if (error) throw error;
      return data as ComplaintComment[];
    },
    enabled: !!complaintId,
  });
};

export const useCreateComplaint = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (complaint: {
      title: string;
      description: string;
      category: string;
      priority: string;
      anonymous: boolean;
      files?: File[];
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      let attachmentUrls: string[] = [];

      // Upload files if provided
      if (complaint.files && complaint.files.length > 0) {
        const uploadPromises = complaint.files.map(async (file) => {
          const fileExt = file.name.split('.').pop();
          const fileName = `${user.id}/${Date.now()}-${Math.random().toString(36).substring(7)}.${fileExt}`;
          
          const { error: uploadError } = await supabase.storage
            .from('complaint-attachments')
            .upload(fileName, file);

          if (uploadError) throw uploadError;

          const { data: { publicUrl } } = supabase.storage
            .from('complaint-attachments')
            .getPublicUrl(fileName);

          return publicUrl;
        });

        attachmentUrls = await Promise.all(uploadPromises);
      }

      const { data, error } = await supabase
        .from("complaints")
        .insert({
          user_id: user.id,
          title: complaint.title,
          description: complaint.description,
          category: complaint.category,
          priority: complaint.priority,
          status: "pending",
          anonymous: complaint.anonymous,
          attachment_urls: attachmentUrls.length > 0 ? attachmentUrls : null,
          reference_id: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["complaints"] });
      toast.success("Complaint submitted successfully");
    },
    onError: (error: any) => {
      toast.error(error.message || "Failed to submit complaint");
    },
  });
};

export const useAddComment = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      complaintId,
      comment,
    }: {
      complaintId: string;
      comment: string;
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      const { data, error } = await supabase
        .from("complaint_comments")
        .insert({
          complaint_id: complaintId,
          user_id: user.id,
          comment: comment,
          is_admin: false,
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({
        queryKey: ["complaint-comments", variables.complaintId],
      });
      toast.success("Comment added successfully!");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Failed to add comment");
    },
  });
};

export const useComplaintStats = () => {
  return useQuery({
    queryKey: ["complaint-stats"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("complaints")
        .select("status");

      if (error) throw error;

      const stats = {
        total: data.length,
        new: data.filter((c) => c.status === "new").length,
        inProgress: data.filter(
          (c) => c.status === "in_review" || c.status === "in_progress"
        ).length,
        resolved: data.filter((c) => c.status === "resolved").length,
      };

      return stats;
    },
  });
};

export const useCallRequest = (complaintId: string) => {
  return useQuery({
    queryKey: ["call-request", complaintId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("call_requests")
        .select("*")
        .eq("complaint_id", complaintId)
        .maybeSingle();

      if (error) throw error;
      return data as CallRequest | null;
    },
    enabled: !!complaintId,
  });
};

export const useCreateCallRequest = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      complaintId,
      notes,
      preferredTime,
    }: {
      complaintId: string;
      notes?: string;
      preferredTime?: string;
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      const { data, error } = await supabase
        .from("call_requests")
        .insert({
          complaint_id: complaintId,
          user_id: user.id,
          notes: notes || null,
          preferred_time: preferredTime || null,
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({
        queryKey: ["call-request", variables.complaintId],
      });
      toast.success("Call request sent successfully!");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Failed to send call request");
    },
  });
};

export const useCancelCallRequest = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (callRequestId: string) => {
      const { data, error } = await supabase
        .from("call_requests")
        .update({ status: "cancelled" })
        .eq("id", callRequestId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({
        queryKey: ["call-request", data.complaint_id],
      });
      toast.success("Call request cancelled");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Failed to cancel call request");
    },
  });
};
